---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
  - name: Check path
    command: ls -l
    register: result

  - name: Display file
    debug:
      msg: "Current file is: {{ result.stdout }}"
  
  - name: Stop running container
    command: docker-compose down
    ignore_errors: yes

  - name: Run docker compose file
    command: docker-compose up

  # - name: Create tag to img
  #   command: docker tag composetest_web ghcr.io/anassamazzar/composetest

  # - name: Push image to dockerhub
  #   command: docker push ghcr.io/anassamazzar/composetest:latest

  # - name: Stop running container
  #   command: docker-compose down
  #   ignore_errors: yes
  # composetest_web